### ISSUE TITLE
Github no mercado de trabalho

### ISSUE THREAD

**Issue by irwingmax** [PHPSPSantos/how-to#13]
Título: **Github no mercado de trabalho**
Palavras-chave: `github`, `mercado`, `carreira`
Nível: *Básico*
Por quê  aprender sobre o tema proposto?
> Acredito que esse assunto tenha como público alvo alunos de faculdade que não conhecem a plataforma ou conhecem mas não dão valor. Acho importante levar a questão de como a plataforma é vista pelas empresas no mercado atual. Assim como também expandir a visão dessa galera que tá parada em currículos impressos e perfis do LinkedIn.

**Comment by gustavoper** [comment]
Para registro, teremos a presença da @marianagomesjob
