### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by leonampd** [PHPSPSantos/how-to#3]
Título: **Git**
Palavras-chave: `git`, `vcs`
Nível: *Básico*
Por quê  aprender sobre o tema proposto?
> O git é uma ferramenta largamente utilizada por desenvolvedores para o gerenciamento de versões de aplicações. Faz parte do dia-a-dia de todo desenvolvedor e torna o processo de desenvolvimento de software muito mais sano.

Material de apoio ou links interessantes:

- [Git](https://git-scm.com/)
- [Repositório oficial](https://github.com/git)
- [Começando com o git](http://blog.alura.com.br/comecando-com-git-aprendendo-versionar/)

**Comment by gustavoper** [comment]
👍

**Comment by leonampd** [comment]
### Live
https://youtu.be/dcQFU-qom8Y
