### ISSUE TITLE
Composer 

### ISSUE THREAD

**Issue by gustavoper** [PHPSPSantos/how-to#4]
Título: **Autoload e Composer**
Palavras-chave: `php`, `composer`
Nível: *Básico*
Por quê  aprender sobre o tema proposto?
> O tema é importante pois aborda dois conceitos-chave para o desenvolvimento de aplicações modernas em php: o autoload e o Composer. Com ele, é possível utilizar namespaces de forma mais prática, bem como bibliotecas de terceiros, entre outros.

Material de apoio ou links interessantes:

- [Composer](https://getcomposer.org/)
- [Composer and Packagist](http://www.phptherightway.com/#composer_and_packagist)

**Comment by leonampd** [comment]
### Live

https://youtu.be/WyDyg3qLkUY
