### ISSUE TITLE
Ambiente de Desenvolvimento

### ISSUE THREAD

**Issue by gustavoper** [PHPSPSantos/how-to#5]
Título: **Ambiente de desenvolvimento**
Palavras-chave: `php`, `development`, `ambiente-desenvolvimento`
Nível: *Básico*
Por quê  aprender sobre o tema proposto?
> Algumas pessoas ainda utilizam servidores legados de desenvolvimento, o objetivo é mostrar um pouco de como montar um ambiente de dev usanod ferramentas modernas, tendo em vista a necessidade (e as limitações) do negócio. Iremos criar um ambiente simples, porém robusto e facilmente customizável. Vamos abordar o vagrant e o docker, enfatizando a segunda opção.

Material de apoio ou links interessantes:

- [Docker](https://www.docker.com/)
- [Vagrant](https://www.vagrantup.com/)

**Comment by leonampd** [comment]
Acompanhe a transmissão ao vivo!

https://www.youtube.com/watch?v=y5juk8Ad0rw

**Comment by gustavoper** [comment]
Ficou pra próxima pq um dos que iria falar morreu no dia hahaha

**Comment by gustavoper** [comment]
Realizada em 19/05

https://www.youtube.com/watch?v=y5juk8Ad0rw
